### ISSUE TITLE
Don't fail when "from_name" cannot be found.

### ISSUE THREAD

**Issue by docwhat** [crazy-max/ghaction-github-labeler#111]
if you set `from_name` but nothing matches it, then it raises and error instead of creating a new label (as if you had not set `from_name`).

As an example, if you setup this:

```yaml
  name: ":pray: help wanted"
  color: "4caf50"
  description: "Extra attention is needed"
  from_name: "help wanted"
```

... but someone deleted "help wanted", then this action fails with:

```
Error: ❌ Label 'help wanted' not found. Cannot rename
```

This is merely annoying at the moment, but if #3 or #9 are completed (or if you have scripts that propagate GitHub configurations to multiple repositories) then this is a must have.
