### ISSUE TITLE
Support multiple config files

### ISSUE THREAD

**Issue by jvalkeal** [crazy-max/ghaction-github-labeler#123]
While trying to label things in multiple repos where most labels are "shared" but there's always repo specific labels it'd be nice if you could point to multiple yml files instead of just one. Action could then merge those together. If want to force all labels to come from this action I'd need to either keep single yml(and merge manually) or keep a bit crazy list of excludes.

This basically shows the annoying thing if trying to use multiple steps:
```
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Shared Labels
        uses: crazy-max/ghaction-github-labeler@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/shared-labels.yml
          skip-delete: false
          dry-run: false
      - name: Project Labels
        uses: crazy-max/ghaction-github-labeler@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/project-labels.yml
          skip-delete: false
          dry-run: false
```
As then you just end up with project labels.

Either expand existing `yaml-file` to use same format as `exclude` or make a new config key:
```
with:
  yaml-file: |
    .github/labels-1.yml
    .github/labels-2.yml
```

I might even find some time to help on this.
