### ISSUE TITLE
Consider using paths in your README.md Workflow example. 

### ISSUE THREAD

**Issue by kopepasah** [crazy-max/ghaction-github-labeler#176]
Currently, the [README.md Workflow example](https://github.com/crazy-max/ghaction-github-labeler#workflow) runs on _every_ push, but it would be better suited to only run on a push matching the path of the YAML configuration file.

### Example

```
on:
  push:
    paths:
      - '.github/labels.yml'
```
