### ISSUE TITLE
Action fails on new repo

### ISSUE THREAD

**Issue by steven-murray** [crazy-max/ghaction-github-labeler#214]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/ghaction-github-labeler/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I am getting an error when running the action on my repo.

### Expected behaviour

For it to pass.

### Actual behaviour

Fails with the following error:

```
/home/runner/work/_actions/crazy-max/ghaction-github-labeler/v5.0.0/webpack:/github-labeler/src/labeler.ts:211
            for (const fileLabel of yield this.fileLabels) {
^
TypeError: (intermediate value) is not iterable
    at Labeler.next (/home/runner/work/_actions/crazy-max/ghaction-github-labeler/v5.0.0/webpack:/github-labeler/src/labeler.ts:211:1)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/crazy-max/ghaction-github-labeler/v5.0.0/webpack:/github-labeler/src/labeler.ts:28:1)
```

### Steps to reproduce

Add `labels.yml` to `.github/` and the attached workflow to `.github/workflows/labeler.yml` then submit as a PR .

### Repository URL

https://github.com/halomod/halomod

### Workflow run URL

https://github.com/halomod/halomod/actions/runs/10077254324/job/27859353630?pr=115

### YAML workflow

```yaml
My `labeler.yml` is:


name: Labeler

on: push

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      content: read

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```
