### ISSUE TITLE
Support `.github` repo `label.yml` file

### ISSUE THREAD

**Issue by casz** [crazy-max/ghaction-github-labeler#3]
Would be great to support the `.github` repo style of deep merging the `label.yml`

So you could have default labels from organization. 👍

**Comment by crazy-max** [comment]
Hi @casz, thanks for your suggestion!

I had thought about integrating this feature but for the moment the scope of a GITHUB_TOKEN is not expanded to the org (yet?). The only way would be to use a GitHub PAT.

Considering this I think we should modify the YAML config to something like:

```yaml
repos:
  - "." # means current repo
  - "myorgname/*"
  - "myusername/*"
  - "myusername/arepo"
labels:
  - name: mylabel
    color: "000000"
  - ...
```
