### ISSUE TITLE
Color 000000

### ISSUE THREAD

**Issue by tenhobi** [crazy-max/ghaction-github-labeler#4]
Please, fix using color `000000` or mention it in the README.

It creates this output:

![image](https://user-images.githubusercontent.com/5287596/67210673-c819bb00-f419-11e9-8cdf-06ef0c59e7e1.png)

for this code:

```yaml
- name: wontfix
  color: 000000
  description: "This will not be worked on"
```
