### ISSUE TITLE
GitHub workflow does not fail when some labels were not applied

### ISSUE THREAD

**Issue by adrianbroher** [crazy-max/ghaction-github-labeler#78]
Hi, I'm currently testing out your github action and I came accross several problems:

When running a workflow this action does not mark the workflow as failed in case a label could not be applied.  Another problem are the error annotations in the workflow overview. You cannot identify the failing label from the annotation alone.  You have to look into the log file to identify the problem.

Workflow file:

```yml
name: Set Project labels
on: push
jobs:
  project-labeler:
    name: Project Labeler
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v1
        with:
          yaml_file: .github/project-labels.yml
          dry_run: ${{ 'refs/heads/master' != github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

project-labels.yml (shortened)
```
- name: "status:testing requested"
  color: "c5def5"
  description: "The Implementation is ready for testing but can't be tested sufficiently by the developer and they request testing by other developers."
```

GitHub action log:
```
🎨 Creating 'status:testing requested' label with color 'c5def5' and desc 'The Implementation is ready for testing but can't be tested sufficiently by the developer and they request testing by other developers.'
##[error]Validation Failed: {"resource":"Label","code":"custom","field":"description","message":"description is too long (maximum is 100 characters)"}
```

Workflow annotations:
![workflow-annotations](https://user-images.githubusercontent.com/84891/80310065-08972e80-87d9-11ea-9b2d-36698d3716ab.png)
